Homework 7 - Data Persistence
yardman438/8ballApp pull request #10
Opened 2021-11-26 15:32 UTC by yardman438

- добавил CoreData
- закинул все контроллеры в UITabBarController
- добавил экран для сохранения истории ответов

2021-11-29 09:39 UTC, ios-school-yalantis requested changes
Нужны доработки: 
- использовать 1 энтити
- все логика персистанса должна быть скрыта в CoredataStack (можно переименовать в DBervice)
- никаких import CoreData в моделях и вьюМоделях не должно быть

2021-11-29 09:39 UTC, ios-school-yalantis commented on 8ballApp/Resources/CoreDataStack.swift
> +    lazy var persistentContainer: NSPersistentContainer = {
make it private

2021-11-29 09:39 UTC, ios-school-yalantis commented on 8ballApp/Managers/CustomAnswerManager.swift
> +import CoreData
CustomAnswerManager ничего не должен знать о CoreData

2021-11-29 09:39 UTC, ios-school-yalantis commented on 8ballApp/Managers/CustomAnswerManager.swift
> +    }
вся логика ветчинка из базы должна быть скрыта в сервисе и методы должны возвращать nonManaged структуры

2021-11-29 09:39 UTC, ios-school-yalantis commented on 8ballApp/Managers/CustomAnswerManager.swift
> +        }
same

2021-11-29 09:39 UTC, ios-school-yalantis commented on 8ballApp/Managers/Models/AnswersDataModel.xcdatamodeld/AnswersDataModel.xcdatamodel/contents
> +</model>
можно обойтись 1 энтити
можно добавить isLocal:Bool атрибут, при запуске приложения можно проверять если это первый запуск то наполнять базу локальными Answer с isLocal == true, если приходит с сети выставлять isLocal = false.

Таким образом останется 1 энтити, а не 2 которые по сути хранят одинаковые данные.

2021-11-29 09:39 UTC, ios-school-yalantis commented on 8ballApp/Managers/UserDefaultsManager.swift
> +    private let defaults = UserDefaults.standard
скрытая зависимость, нужно инжектить через инициализатор, так можно как дефолтный параметр

2021-11-29 09:39 UTC, ios-school-yalantis commented on 8ballApp/Resources/CoreDataStack.swift
> +}
для извлечения объектов можно использовать дженерик метод 
```
    private func getObjects<T: NSManagedObject>(
        _ request: NSFetchRequest<T>,
        completion: @escaping (Result<[T]>) -> Void
    ) {
        let context = yourContext
        context.perform {
            do {
                let result = try context.fetch(request) as! [T]
                completion(.success(result))
            } catch let error {
                completion(.failure(error))
            }
        }
    }
}
```

далее добавить публичные методы в которых будут формироваться NSFetchRequest, извлекается объекты с помощью метода выше, преобразовывается в Answer структуры

преобразование должно быть реализовано в экстеншене к структуре и к ManagedObject
 
 пример:
 ```
 extension Managed {
      func toAnswer() -> Answer {
          create answer from Managed answer here
     }
}
 ```

2021-11-29 09:39 UTC, ios-school-yalantis commented on 8ballApp/Managers/AnswerHistoryManager.swift
> +import CoreData
не должно быть import CoreData

2021-11-29 09:39 UTC, ios-school-yalantis commented on 8ballApp/Resources/AppDelegate.swift
> +import CoreData
не должно быть import CoreData
UIAppDelegate должен заниматься только отправки ивентов системы! Так же стартовать флоу приложения 
Принцип эдиной отвецтвенности.

2021-11-30 16:04 UTC, yardman438 commented
Спасибо за фидбек
Исправил

2021-11-30 18:07 UTC, ios-school-yalantis commented on 8ballApp/Flows/History/HistoryScreenViewController.swift
> +        DispatchQueue.main.async {
а зачем тут DispatchQueue.main.async? метод viewWillAppear и так вызывается в главном потоке

2021-11-30 18:07 UTC, ios-school-yalantis commented on 8ballApp/Managers/DBService.swift
> +    private func saveContext () {
я бы функцию переименовала как saveBackgroundContext, а еще лучше добавила как параметр сам контекст. saveBackgroundContext - покажет явно, что это метод сохранения именно бекграунд контекста. А сам контекст как параметр - функция будет более гибкой, так как вдруг в какой-то момент времени у тебя будет несколько бекраунд контекстов. Тогда эта функция будет универсальная

2021-11-30 20:17 UTC, ios-school-yalantis approved these changes
Обязательно поправь последний комменты и можно мержить!

2021-11-30 20:17 UTC, ios-school-yalantis commented on 8ballApp/Managers/Models/DBAnswer.swift
> +public class DBAnswer: NSManagedObject {
переименуй DBAnswer -> ManagedAnswer и удали ManagedAnswer struct не вижу в ней смысла.

ManagedAnswer -> Answer -> AnswerPresentable(Для каждой UI может быть своя)

2021-11-30 20:17 UTC, ios-school-yalantis commented on 8ballApp/Managers/Models/Answer.swift
> +    func toManaged(isLocal: Bool) -> ManagedAnswer {
только наверное так не получится сделать, это сейчас понял

потому что для создания ManagedAnswer нужен будет контекст, создание Managed Answer должно быть скрыто внутри DBServce

2021-11-30 20:17 UTC, ios-school-yalantis commented on 8ballApp/Managers/DBService.swift
> +    private var answers: [DBAnswer] = []
зачем хранить массив answers? если его можно вытащить из базы

2021-11-30 20:17 UTC, ios-school-yalantis commented on 8ballApp/Managers/DBService.swift
> +                let result = try self.backgroundContext.fetch(request)
для извлечения нужно использовать mainContext так как мы будем работать с данями на мейн потоке

для записи можно использовать бэкграунд контекст

2021-12-04 11:41 UTC, merged