Homework #2 (branch: Feature/refactoring)
yardman438/8ballApp pull request #4
Opened 2021-11-09 09:45 UTC by yardman438

Данный PR относится ко второй домашней работе.
- был проделан рефакторинг
- созданы абстракции и присуждены уровни доступа к свойствам и методам
- пересоздан заново второй экран (так как на момент сдачи тестового я не успел его сделать, поэтому подумал что надо закончить в течении учебы)

2021-11-09 19:43 UTC, ios-school-yalantis requested changes

2021-11-09 19:43 UTC, ios-school-yalantis commented on 8ballApp/Models/CustomAnswer.swift
> +    }
из названия функции не понятно что кода должно сетится, она просто возвращает значение, в общем выглядит как get

2021-11-09 19:43 UTC, ios-school-yalantis commented on 8ballApp/ViewControllers/MainViewController.swift
> +    private var answerManager: Networking = AnswerManager()
зависимости должны быть переданы из вне

2021-11-10 15:13 UTC, yardman438 commented on 8ballApp/Models/CustomAnswer.swift
> +    }
Исправил и в следующих кометах планирую использовать realm для подготовленных ответов

2021-11-10 15:16 UTC, yardman438 commented on 8ballApp/ViewControllers/MainViewController.swift
> +    private var answerManager: Networking = AnswerManager()
Исправил
Использовал property injection, так как при попытке провести constructor injection приложение крашит из-за того, что используется сториборд

2021-11-10 17:25 UTC, ios-school-yalantis approved these changes
все верно, можно мержить

2021-11-10 17:28 UTC, merged